import 'dart:core';
import 'package:tfgapp/src/models/country.dart';

class Countries {
  static final List<Country> countries = [
    Country(code: "ES", name: "Espa\u00f1a"),
    Country(code: "AF", name: "Afganist\u00e1n"),
    Country(code: "AL", name: "Albania"),
    Country(code: "DE", name: "Alemania"),
    Country(code: "AD", name: "Andorra"),
    Country(code: "AO", name: "Angola"),
    Country(code: "AI", name: "Anguila"),
    Country(code: "AQ", name: "Ant\u00e1rtida"),
    Country(code: "AG", name: "Antigua y Barbuda"),
    Country(code: "SA", name: "Arabia Saud\u00ed"),
    Country(code: "DZ", name: "Argelia"),
    Country(code: "AR", name: "Argentina"),
    Country(code: "AM", name: "Armenia"),
    Country(code: "AW", name: "Aruba"),
    Country(code: "AU", name: "Australia"),
    Country(code: "AT", name: "Austria"),
    Country(code: "AZ", name: "Azerbaiy\u00e1n"),
    Country(code: "BS", name: "Bahamas"),
    Country(code: "BD", name: "Banglad\u00e9s"),
    Country(code: "BB", name: "Barbados"),
    Country(code: "BH", name: "Bar\u00e9in"),
    Country(code: "BE", name: "B\u00e9lgica"),
    Country(code: "BZ", name: "Belice"),
    Country(code: "BJ", name: "Ben\u00edn"),
    Country(code: "BM", name: "Bermudas"),
    Country(code: "BY", name: "Bielorrusia"),
    Country(code: "BO", name: "Bolivia"),
    Country(code: "BA", name: "Bosnia y Herzegovina"),
    Country(code: "BW", name: "Botsuana"),
    Country(code: "BR", name: "Brasil"),
    Country(code: "BN", name: "Brun\u00e9i"),
    Country(code: "BG", name: "Bulgaria"),
    Country(code: "BF", name: "Burkina Faso"),
    Country(code: "BI", name: "Burundi"),
    Country(code: "BT", name: "But\u00e1n"),
    Country(code: "CV", name: "Cabo Verde"),
    Country(code: "KH", name: "Camboya"),
    Country(code: "CM", name: "Camer\u00fan"),
    Country(code: "CA", name: "Canad\u00e1"),
    Country(code: "BQ", name: "Caribe neerland\u00e9s"),
    Country(code: "QA", name: "Catar"),
    Country(code: "TD", name: "Chad"),
    Country(code: "CZ", name: "Chequia"),
    Country(code: "CL", name: "Chile"),
    Country(code: "CN", name: "China"),
    Country(code: "CY", name: "Chipre"),
    Country(code: "VA", name: "Ciudad del Vaticano"),
    Country(code: "CO", name: "Colombia"),
    Country(code: "KM", name: "Comoras"),
    Country(code: "CG", name: "Congo"),
    Country(code: "KP", name: "Corea del Norte"),
    Country(code: "KR", name: "Corea del Sur"),
    Country(code: "CR", name: "Costa Rica"),
    Country(code: "CI", name: "C\u00f4te d\u2019Ivoire"),
    Country(code: "HR", name: "Croacia"),
    Country(code: "CU", name: "Cuba"),
    Country(code: "CW", name: "Curazao"),
    Country(code: "DK", name: "Dinamarca"),
    Country(code: "DM", name: "Dominica"),
    Country(code: "EC", name: "Ecuador"),
    Country(code: "EG", name: "Egipto"),
    Country(code: "SV", name: "El Salvador"),
    Country(code: "AE", name: "Emiratos \u00c1rabes Unidos"),
    Country(code: "ER", name: "Eritrea"),
    Country(code: "SK", name: "Eslovaquia"),
    Country(code: "SI", name: "Eslovenia"),
    Country(code: "US", name: "Estados Unidos"),
    Country(code: "EE", name: "Estonia"),
    Country(code: "SZ", name: "Esuatini"),
    Country(code: "ET", name: "Etiop\u00eda"),
    Country(code: "PH", name: "Filipinas"),
    Country(code: "FI", name: "Finlandia"),
    Country(code: "FJ", name: "Fiyi"),
    Country(code: "FR", name: "Francia"),
    Country(code: "GA", name: "Gab\u00f3n"),
    Country(code: "GM", name: "Gambia"),
    Country(code: "GE", name: "Georgia"),
    Country(code: "GH", name: "Ghana"),
    Country(code: "GI", name: "Gibraltar"),
    Country(code: "GD", name: "Granada"),
    Country(code: "GR", name: "Grecia"),
    Country(code: "GL", name: "Groenlandia"),
    Country(code: "GP", name: "Guadalupe"),
    Country(code: "GU", name: "Guam"),
    Country(code: "GT", name: "Guatemala"),
    Country(code: "GF", name: "Guayana Francesa"),
    Country(code: "GG", name: "Guernsey"),
    Country(code: "GN", name: "Guinea"),
    Country(code: "GQ", name: "Guinea Ecuatorial"),
    Country(code: "GW", name: "Guinea-Bis\u00e1u"),
    Country(code: "GY", name: "Guyana"),
    Country(code: "HT", name: "Hait\u00ed"),
    Country(code: "HN", name: "Honduras"),
    Country(code: "HU", name: "Hungr\u00eda"),
    Country(code: "IN", name: "India"),
    Country(code: "ID", name: "Indonesia"),
    Country(code: "IQ", name: "Irak"),
    Country(code: "IR", name: "Ir\u00e1n"),
    Country(code: "IE", name: "Irlanda"),
    Country(code: "BV", name: "Isla Bouvet"),
    Country(code: "IM", name: "Isla de Man"),
    Country(code: "CX", name: "Isla de Navidad"),
    Country(code: "NF", name: "Isla Norfolk"),
    Country(code: "IS", name: "Islandia"),
    Country(code: "AX", name: "Islas \u00c5land"),
    Country(code: "KY", name: "Islas Caim\u00e1n"),
    Country(code: "CC", name: "Islas Cocos"),
    Country(code: "CK", name: "Islas Cook"),
    Country(code: "FO", name: "Islas Feroe"),
    Country(code: "GS", name: "Islas Georgia del Sur y Sandwich del Sur"),
    Country(code: "HM", name: "Islas Heard y McDonald"),
    Country(code: "FK", name: "Islas Malvinas"),
    Country(code: "MP", name: "Islas Marianas del Norte"),
    Country(code: "MH", name: "Islas Marshall"),
    Country(code: "UM", name: "Islas menores alejadas de EE. UU."),
    Country(code: "PN", name: "Islas Pitcairn"),
    Country(code: "SB", name: "Islas Salom\u00f3n"),
    Country(code: "TC", name: "Islas Turcas y Caicos"),
    Country(code: "VG", name: "Islas V\u00edrgenes Brit\u00e1nicas"),
    Country(code: "VI", name: "Islas V\u00edrgenes de EE. UU."),
    Country(code: "IL", name: "Israel"),
    Country(code: "IT", name: "Italia"),
    Country(code: "JM", name: "Jamaica"),
    Country(code: "JP", name: "Jap\u00f3n"),
    Country(code: "JE", name: "Jersey"),
    Country(code: "JO", name: "Jordania"),
    Country(code: "KZ", name: "Kazajist\u00e1n"),
    Country(code: "KE", name: "Kenia"),
    Country(code: "KG", name: "Kirguist\u00e1n"),
    Country(code: "KI", name: "Kiribati"),
    Country(code: "KW", name: "Kuwait"),
    Country(code: "LA", name: "Laos"),
    Country(code: "LS", name: "Lesoto"),
    Country(code: "LV", name: "Letonia"),
    Country(code: "LB", name: "L\u00edbano"),
    Country(code: "LR", name: "Liberia"),
    Country(code: "LY", name: "Libia"),
    Country(code: "LI", name: "Liechtenstein"),
    Country(code: "LT", name: "Lituania"),
    Country(code: "LU", name: "Luxemburgo"),
    Country(code: "MK", name: "Macedonia del Norte"),
    Country(code: "MG", name: "Madagascar"),
    Country(code: "MY", name: "Malasia"),
    Country(code: "MW", name: "Malaui"),
    Country(code: "MV", name: "Maldivas"),
    Country(code: "ML", name: "Mali"),
    Country(code: "MT", name: "Malta"),
    Country(code: "MA", name: "Marruecos"),
    Country(code: "MQ", name: "Martinica"),
    Country(code: "MU", name: "Mauricio"),
    Country(code: "MR", name: "Mauritania"),
    Country(code: "YT", name: "Mayotte"),
    Country(code: "MX", name: "M\u00e9xico"),
    Country(code: "FM", name: "Micronesia"),
    Country(code: "MD", name: "Moldavia"),
    Country(code: "MC", name: "M\u00f3naco"),
    Country(code: "MN", name: "Mongolia"),
    Country(code: "ME", name: "Montenegro"),
    Country(code: "MS", name: "Montserrat"),
    Country(code: "MM", name: "Myanmar (Birmania)"),
    Country(code: "NA", name: "Namibia"),
    Country(code: "NR", name: "Nauru"),
    Country(code: "NP", name: "Nepal"),
    Country(code: "NI", name: "Nicaragua"),
    Country(code: "NE", name: "N\u00edger"),
    Country(code: "NG", name: "Nigeria"),
    Country(code: "NU", name: "Niue"),
    Country(code: "NO", name: "Noruega"),
    Country(code: "NC", name: "Nueva Caledonia"),
    Country(code: "NZ", name: "Nueva Zelanda"),
    Country(code: "OM", name: "Om\u00e1n"),
    Country(code: "NL", name: "Pa\u00edses Bajos"),
    Country(code: "PK", name: "Pakist\u00e1n"),
    Country(code: "PW", name: "Palaos"),
    Country(code: "PA", name: "Panam\u00e1"),
    Country(code: "PG", name: "Pap\u00faa Nueva Guinea"),
    Country(code: "PY", name: "Paraguay"),
    Country(code: "PE", name: "Per\u00fa"),
    Country(code: "PF", name: "Polinesia Francesa"),
    Country(code: "PL", name: "Polonia"),
    Country(code: "PT", name: "Portugal"),
    Country(code: "PR", name: "Puerto Rico"),
    Country(code: "HK", name: "RAE de Hong Kong (China)"),
    Country(code: "MO", name: "RAE de Macao (China)"),
    Country(code: "GB", name: "Reino Unido"),
    Country(code: "CF", name: "Rep\u00fablica Centroafricana"),
    Country(code: "CD", name: "Rep\u00fablica Democr\u00e1tica del Congo"),
    Country(code: "DO", name: "Rep\u00fablica Dominicana"),
    Country(code: "RE", name: "Reuni\u00f3n"),
    Country(code: "RW", name: "Ruanda"),
    Country(code: "RO", name: "Ruman\u00eda"),
    Country(code: "RU", name: "Rusia"),
    Country(code: "EH", name: "S\u00e1hara Occidental"),
    Country(code: "WS", name: "Samoa"),
    Country(code: "AS", name: "Samoa Americana"),
    Country(code: "BL", name: "San Bartolom\u00e9"),
    Country(code: "KN", name: "San Crist\u00f3bal y Nieves"),
    Country(code: "SM", name: "San Marino"),
    Country(code: "MF", name: "San Mart\u00edn"),
    Country(code: "PM", name: "San Pedro y Miquel\u00f3n"),
    Country(code: "VC", name: "San Vicente y las Granadinas"),
    Country(code: "SH", name: "Santa Elena"),
    Country(code: "LC", name: "Santa Luc\u00eda"),
    Country(code: "ST", name: "Santo Tom\u00e9 y Pr\u00edncipe"),
    Country(code: "SN", name: "Senegal"),
    Country(code: "RS", name: "Serbia"),
    Country(code: "SC", name: "Seychelles"),
    Country(code: "SL", name: "Sierra Leona"),
    Country(code: "SG", name: "Singapur"),
    Country(code: "SX", name: "Sint Maarten"),
    Country(code: "SY", name: "Siria"),
    Country(code: "SO", name: "Somalia"),
    Country(code: "LK", name: "Sri Lanka"),
    Country(code: "ZA", name: "Sud\u00e1frica"),
    Country(code: "SD", name: "Sud\u00e1n"),
    Country(code: "SS", name: "Sud\u00e1n del Sur"),
    Country(code: "SE", name: "Suecia"),
    Country(code: "CH", name: "Suiza"),
    Country(code: "SR", name: "Surinam"),
    Country(code: "SJ", name: "Svalbard y Jan Mayen"),
    Country(code: "TH", name: "Tailandia"),
    Country(code: "TW", name: "Taiw\u00e1n"),
    Country(code: "TZ", name: "Tanzania"),
    Country(code: "TJ", name: "Tayikist\u00e1n"),
    Country(
        code: "IO",
        name: "Territorio Brit\u00e1nico del Oc\u00e9ano \u00cdndico"),
    Country(code: "TF", name: "Territorios Australes Franceses"),
    Country(code: "PS", name: "Territorios Palestinos"),
    Country(code: "TL", name: "Timor-Leste"),
    Country(code: "TG", name: "Togo"),
    Country(code: "TK", name: "Tokelau"),
    Country(code: "TO", name: "Tonga"),
    Country(code: "TT", name: "Trinidad y Tobago"),
    Country(code: "TN", name: "T\u00fanez"),
    Country(code: "TM", name: "Turkmenist\u00e1n"),
    Country(code: "TR", name: "Turqu\u00eda"),
    Country(code: "TV", name: "Tuvalu"),
    Country(code: "UA", name: "Ucrania"),
    Country(code: "UG", name: "Uganda"),
    Country(code: "UY", name: "Uruguay"),
    Country(code: "UZ", name: "Uzbekist\u00e1n"),
    Country(code: "VU", name: "Vanuatu"),
    Country(code: "VE", name: "Venezuela"),
    Country(code: "VN", name: "Vietnam"),
    Country(code: "WF", name: "Wallis y Futuna"),
    Country(code: "YE", name: "Yemen"),
    Country(code: "DJ", name: "Yibuti"),
    Country(code: "ZM", name: "Zambia"),
    Country(code: "ZW", name: "Zimbabue")
  ];
}
