import 'package:tfgapp/src/models/provider.dart';
import 'dart:core';

class Providers {
  static final List<Provider> providers = [
    Provider(code: "201", name: "Mubi Amazon Channel"),
    Provider(code: "393", name: "FlixOlé"),
    Provider(code: "684", name: "FlixOlé Amazon Channel"),
    Provider(code: "149", name: "Movistar Plus"),
    Provider(code: "62", name: "Atres Player"),
    Provider(code: "2", name: "Apple iTunes"),
    Provider(code: "3", name: "Google Play Movies"),
    Provider(code: "10", name: "Amazon Video"),
    Provider(code: "68", name: "Microsoft Store"),
    Provider(code: "588", name: "MGM Amazon Channel"),
    Provider(code: "257", name: "fuboTV"),
    Provider(code: "223", name: "hayu"),
    Provider(code: "445", name: "Classix"),
    Provider(code: "188", name: "YouTube Premium"),
    Provider(code: "701", name: "FilmBox+"),
    Provider(code: "283", name: "Crunchyroll"),
    Provider(code: "692", name: "Cultpix"),
    Provider(code: "457", name: "VIX"),
    Provider(code: "190", name: "Curiosity Stream"),
    Provider(code: "194", name: "Starz Play Amazon Channel"),
    Provider(code: "546", name: "WOW Presents Plus"),
    Provider(code: "551", name: "Magellan TV"),
    Provider(code: "554", name: "BroadwayHD"),
    Provider(code: "444", name: "Dekkoo"),
    Provider(code: "456", name: "Mitele"),
    Provider(code: "315", name: "Hoichoi"),
    Provider(code: "300", name: "Pluto TV"),
    Provider(code: "296", name: "Hayu Amazon Channel"),
    Provider(code: "524", name: "Discovery Plus"),
    Provider(code: "43", name: "Starz"),
    Provider(code: "607", name: "OUTtv Amazon Channel"),
    Provider(code: "262", name: "Noggin Amazon Channel"),
    Provider(code: "196", name: "AcornTV Amazon Channel"),
    Provider(code: "538", name: "Plex"),
    Provider(code: "100", name: "GuideDoc"),
    Provider(code: "534", name: "Argo"),
    Provider(code: "677", name: "Eventive"),
    Provider(code: "475", name: "DOCSVILLE"),
    Provider(code: "559", name: "Filmzie"),
    Provider(code: "567", name: "True Story"),
    Provider(code: "569", name: "DocAlliance Films"),
    Provider(code: "689", name: "TVCortos Amazon Channel"),
  ];
}
